### ISSUE TITLE
xenon-cli 3.0.4 currently not accessible with conda

### ISSUE THREAD

**Issue by lsantuari** [xenon-middleware/xenon-cli#73]
Is the conda package under maintanance?

`conda 4.8.2`

```
PackagesNotFoundError: The following packages are not available from current channels:

  - xenon-cli

Current channels:

  - https://conda.anaconda.org/nlesc/osx-64
  - https://conda.anaconda.org/nlesc/noarch
  - https://conda.anaconda.org/bioconda/osx-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://conda.anaconda.org/r/osx-64
  - https://conda.anaconda.org/r/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

**Comment by sverhoeven** [comment]
It is for linux, but not yet for OSX. Will have look to make it noarch, but had problems with it [before](https://github.com/xenon-middleware/xenon-cli/issues/49)

**Comment by sverhoeven** [comment]
I just create a beta version of a noarch xenon-cli conda package.

Could you test it with `conda install -c conda-forge -c nlesc xenon-cli=3.0.5beta1`?

**Comment by lsantuari** [comment]
Thank you, Stefan. The installation of `xenon-cli=3.0.5beta1` works.
I am usually using it on a Linux system, but I am also testing it on OSX.

**Comment by sverhoeven** [comment]
Made 3.0.5 available on https://anaconda.org/nlesc/xenon-cli
